post:
  summary: /api/federation/configuration API
  description: |
    This API gathers the federation configuration about a service.

    The authorization server implementation should
    retrieve the value of the <code>action</code>
    response parameter from the API response and take the following steps
    according to the value.
    
    <h3><code>OK</code></h3>
  
    When the value of the <code> action</code> response
    parameter is <code>OK</code>, it means that Authlete
    could prepare an entity configuration successfully.
  
    In this case, the implementation of the entity configuration endpoint of the
    authorization server should return an HTTP response to the client application
    with the HTTP status code "`200 OK`" and the content type
    "`application/entity-statement+jwt`". The message body (= an entity
    configuration in the JWT format) of the response has been prepared by
    Authlete's `/federation/configuration` API and it is available as the
    <code>responseContent</code> response parameter.

    The implementation of the entity configuration endpoint can construct an
    HTTP response by doing like below.
    
    <pre style="border: solid 1px black; padding: 0.5em;">
    200 OK
    Content-Type: application/entity-statement+jwt
    (Other HTTP headers)
  
    <i>(the value of the responseContent response parameter)</i></pre>
    
    <h3><code>NOT_FOUND</code></h3>
   
    When the value of the <code> action</code> response
    parameter is <code>NOT_FOUND</code>, it means that
    the service configuration has not enabled the feature of <a href=
    "https://openid.net/specs/openid-connect-federation-1_0.html">OpenID Connect
    Federation 1.0</a> and so the client application should have not access the
    entity configuration endpoint.

    In this case, the implementation of the entity configuration endpoint of the
    authorization server should return an HTTP response to the client application
    with the HTTP status code "`404 Not Found`" and the content type
    "`application/json`". The message body (= error information in the JSON
    format) of the response has been prepared by Authlete's
    `/federation/configuration` API and it is available as the
    <code>responseContent</code> response parameter.

    The implementation of the entity configuration endpoint can construct an
    HTTP response by doing like below.

    <pre style="border: solid 1px black; padding: 0.5em;">
    404 Not Found
    Content-Type: application/json
    (Other HTTP headers)
   
    <i>(the value of the responseContent response parameter)</i></pre>
   
    <h3><code>INTERNAL_SERVER_ERROR</code></h3>
   
    could prepare an entity configuration successfully.
   
    In this case, the implementation of the entity configuration endpoint of the
    authorization server should return an HTTP response to the client application
    with the HTTP status code "`200 OK`" and the content type
    "`application/entity-statement+jwt`". The message body (= an entity
    configuration in the JWT format) of the response has been prepared by
    Authlete's `/federation/configuration` API and it is available as the
    <code>responseContent</code> response parameter.

    The implementation of the entity configuration endpoint can construct an
    HTTP response by doing like below.

    <pre style="border: solid 1px black; padding: 0.5em;">
    200 OK
    Content-Type: application/entity-statement+jwt
    (Other HTTP headers)
   
    <i>(the value of the responseContent response parameter)</i></pre>
   
  
    </details>

  security:
    - ServiceCredentials: []
  requestBody:
    content:
      application/json:
        schema:
          type: object
  responses:
    '200':
      description: ""
      content:
        application/json:
          schema:
            $ref: ../model/response/federation_configuration_response.yaml
    '400':
      $ref: ../model/response/400.yaml
    '401':
      $ref: ../model/response/401.yaml
    '403':
      $ref: ../model/response/403.yaml
    '500':
      $ref: ../model/response/500.yaml
  operationId: 'federation_configuration_api'
  x-code-samples:
    - lang: shell
      label: curl
      source: |
        curl -v https://api.authlete.com/api/federation/configuration \
        -u '21653835348762:uE4NgqeIpuSV_XejQ7Ds3jsgA1yXhjR1MXJ1LbPuyls'

    - lang: java
      label: java
      source: |
        AuthleteConfiguration conf = ...;
        AuthleteApi api = AuthleteApiFactory.create(conf);

        api.getFederationConfiguration();

    - lang: cs
      label: C#
      source: |
        IAuthleteConfiguration conf = ...;
        IAuthleteApi api = new AuthleteApi(conf);

        await api.GetFederationConfiguration(true);

    - lang: php
      label: PHP
      source: |
        $conf = ...;
        $api = new AuthleteApiImpl($conf);

        $api.getFederationConfiguration(true);

    - lang: ruby
      source: |
        conf = ...
        api = Authlete::Api.new(conf)

        api.get_federation_configuration(pretty: true)

    - lang: python
      source: |
        conf = ...
        api = AuthleteApiImpl(conf)

        api.getFederationConfiguration(True)

    - lang: go
      source: |
        conf := ...
        api := api.New(&conf)

        api.GetFederationConfiguration(true)

    - lang: ts
      label: deno
      source: |
        const conf: AuthleteConfiguration = ...;
        const api: AuthleteApi = new AuthleteApiImpl(conf);

        await api.getFederationConfiguration(true);
  tags:
    - Federation Endpoint
