stages:
  - generate client
  - delete review client
  - push client

include: '.gitlab-ci/build-shared.yml'

variables:
  CLIENT_REPO: openapi-for-typescript
  GENERATOR_IMAGE: openapitools/openapi-generator-cli:v6.2.1
  GENERATOR_CONFIG: typescript-client-codegen.yml
  GITHUB_SSH_PUSH_KEY: ${TS_SSH_PUSH_KEY}
  ENV_PREFIX: ts
  GIT_CLEAN_MASK: "*/*.ts */apis */models */openapi-generator* */*.json"

.check version already published:
  image: node:latest
  stage: generate client
  allow_failure: true
  extends:
    - .prepare_github_step
  rules:
    - if: $CI_COMMIT_BRANCH
      changes:
        - specs/**/*
        - typescript-client-codegen.yml
  script:
    - git clone git@github.com:authlete/${CLIENT_REPO}.git
    - cd ${CLIENT_REPO}
    - git checkout $CI_COMMIT_BRANCH || true
    - version=$(npm pkg get version)
    - version=${version%\"}
    - version=${version#\"}
    - npm install -g version-exists
    - (! version-exists @authlete/openapi-client $version)

.push client:
  image: node:latest
  stage: push client
  needs: ["check version already published"]
  only:
    refs:
      - master
    changes:
        - specs/**/*
        - typescript-client-codegen.yml
  extends:
    - .prepare_github_step
  script:
    - git clone git@github.com:authlete/${CLIENT_REPO}.git
    - cd ${CLIENT_REPO}
    - git checkout $CI_COMMIT_BRANCH || true
    - npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
    - npm install
    - npm publish --access public

