
.prepare_github_step:
  before_script:
    - mkdir ~/.ssh/ || true
    - echo "${CI_KNOWN_HOSTS}" > ~/.ssh/known_hosts
    - echo "${GITHUB_SSH_PUSH_KEY}" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - git config user.email "ci@authlete.com"
    - git config user.name "CI"

generate client:
  stage: generate client
  extends:
    - .prepare_github_step
  script:
    - git clone git@github.com:authlete/${CLIENT_REPO}.git
    - for i in ${GIT_CLEAN_MASK}; do echo "$i"; find ${CLIENT_REPO} -iname $i -delete;  done
    - docker run --rm -v ${PWD}:/local ${GENERATOR_IMAGE} batch /local/${GENERATOR_CONFIG}
    - cd ${CLIENT_REPO}
    - go install golang.org/x/tools/cmd/goimports@latest
    - $HOME/go/bin/goimports -w *.go
    - go mod download
    - go test -v -cover ./...
    - git config user.email "ci@authlete.com"
    - git config user.name "CI"
    - |
      git checkout -b ${TARGET_BRANCH} || true
      git add .
      git commit -m "Authlete CI - ${CI_COMMIT_SHA}" || true
      git push origin ${TARGET_BRANCH}:refs/heads/${TARGET_BRANCH} --force
      


