type: string
description: |
  The application type. The value of this property affects the validation steps for a redirect URI.
  See the description about `redirectUris` property for more details.
enum:
  - WEB
  - NATIVE
