# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redoc.ly/docs/cli/ for more information.
model/response/client_secret_refresh_response.yaml:
  no-invalid-media-type-examples:
    - '#/content/application~1json/example/newClientSecret'
    - '#/content/application~1json/example/oldClientSecret'
    - '#/content/application~1json/example/resultCode'
    - '#/content/application~1json/example/resultMessage'
model/response/client_secret_update_response.yaml:
  no-invalid-media-type-examples:
    - '#/content/application~1json/example/newClientSecret'
    - '#/content/application~1json/example/oldClientSecret'
    - '#/content/application~1json/example/resultCode'
    - '#/content/application~1json/example/resultMessage'
model/response/authorization_response.yaml:
  no-invalid-media-type-examples:
    - '#/content/application~1json/example/acrEssential'
    - '#/content/application~1json/example/action'
    - '#/content/application~1json/example/client'
    - '#/content/application~1json/example/clientIdAliasUsed'
    - '#/content/application~1json/example/display'
    - '#/content/application~1json/example/maxAge'
    - '#/content/application~1json/example/scopes'
    - '#/content/application~1json/example/service'
    - '#/content/application~1json/example/ticket'
    - '#/content/application~1json/example/resultCode'
    - '#/content/application~1json/example/resultMessage'
model/response/authorization_fail_response.yaml:
  no-invalid-media-type-examples:
    - '#/content/application~1json/example/action'
    - '#/content/application~1json/example/responseContent'
    - '#/content/application~1json/example/resultCode'
    - '#/content/application~1json/example/resultMessage'
model/response/authorization_issue_response.yaml:
  no-invalid-media-type-examples:
    - '#/content/application~1json/example/accessTokenDuration'
    - '#/content/application~1json/example/accessTokenExpiresAt'
    - '#/content/application~1json/example/action'
    - '#/content/application~1json/example/authorizationCode'
    - '#/content/application~1json/example/responseContent'
    - '#/content/application~1json/example/resultCode'
    - '#/content/application~1json/example/resultMessage'
model/response/token_response.yaml:
  no-invalid-media-type-examples:
    - '#/content/application~1json/example/accessToken'
    - '#/content/application~1json/example/accessTokenDuration'
    - '#/content/application~1json/example/accessTokenExpiresAt'
    - '#/content/application~1json/example/action'
    - '#/content/application~1json/example/clientAttributes'
    - '#/content/application~1json/example/clientId'
    - '#/content/application~1json/example/clientIdAlias'
    - '#/content/application~1json/example/clientIdAliasUsed'
    - '#/content/application~1json/example/grantType'
    - '#/content/application~1json/example/refreshToken'
    - '#/content/application~1json/example/refreshTokenDuration'
    - '#/content/application~1json/example/refreshTokenExpiresAt'
    - '#/content/application~1json/example/responseContent'
    - '#/content/application~1json/example/scopes'
    - '#/content/application~1json/example/serviceAttributes'
    - '#/content/application~1json/example/subject'
    - '#/content/application~1json/example/resultCode'
    - '#/content/application~1json/example/resultMessage'
model/response/token_fail_response.yaml:
  no-invalid-media-type-examples:
    - '#/content/application~1json/example/action'
    - '#/content/application~1json/example/responseContent'
    - '#/content/application~1json/example/resultCode'
    - '#/content/application~1json/example/resultMessage'
model/response/token_issue_response.yaml:
  no-invalid-media-type-examples:
    - '#/content/application~1json/example/accessToken'
    - '#/content/application~1json/example/accessTokenDuration'
    - '#/content/application~1json/example/accessTokenExpiresAt'
    - '#/content/application~1json/example/action'
    - '#/content/application~1json/example/clientAttributes'
    - '#/content/application~1json/example/clientId'
    - '#/content/application~1json/example/clientIdAlias'
    - '#/content/application~1json/example/clientIdAliasUsed'
    - '#/content/application~1json/example/refreshToken'
    - '#/content/application~1json/example/refreshTokenDuration'
    - '#/content/application~1json/example/refreshTokenExpiresAt'
    - '#/content/application~1json/example/responseContent'
    - '#/content/application~1json/example/serviceAttributes'
    - '#/content/application~1json/example/subject'
    - '#/content/application~1json/example/resultCode'
    - '#/content/application~1json/example/resultMessage'
model/response/introspection_response.yaml:
  no-invalid-media-type-examples:
    - '#/content/application~1json/example/action'
    - '#/content/application~1json/example/clientAttributes'
    - '#/content/application~1json/example/clientId'
    - '#/content/application~1json/example/clientIdAlias'
    - '#/content/application~1json/example/clientIdAliasUsed'
    - '#/content/application~1json/example/existent'
    - '#/content/application~1json/example/expiresAt'
    - '#/content/application~1json/example/refreshable'
    - '#/content/application~1json/example/responseContent'
    - '#/content/application~1json/example/scopes'
    - '#/content/application~1json/example/serviceAttributes'
    - '#/content/application~1json/example/subject'
    - '#/content/application~1json/example/sufficient'
    - '#/content/application~1json/example/usable'
    - '#/content/application~1json/example/resultCode'
    - '#/content/application~1json/example/resultMessage'
model/response/standard_introspection_response.yaml:
  no-invalid-media-type-examples:
    - '#/content/application~1json/example/action'
    - '#/content/application~1json/example/responseContent'
    - '#/content/application~1json/example/resultCode'
    - '#/content/application~1json/example/resultMessage'
model/response/revocation_response.yaml:
  no-invalid-media-type-examples:
    - '#/content/application~1json/example/action'
    - '#/content/application~1json/example/resultCode'
    - '#/content/application~1json/example/resultMessage'
model/response/userinfo_response.yaml:
  no-invalid-media-type-examples:
    - '#/content/application~1json/example/action'
    - '#/content/application~1json/example/clientId'
    - '#/content/application~1json/example/clientIdAliasUsed'
    - '#/content/application~1json/example/scopes'
    - '#/content/application~1json/example/subject'
    - '#/content/application~1json/example/token'
    - '#/content/application~1json/example/resultCode'
    - '#/content/application~1json/example/resultMessage'
model/response/userinfo_issue_response.yaml:
  no-invalid-media-type-examples:
    - '#/content/application~1json/example/action'
    - '#/content/application~1json/example/responseContent'
    - '#/content/application~1json/example/resultCode'
    - '#/content/application~1json/example/resultMessage'
model/response/client_registration_response.yaml:
  no-invalid-media-type-examples:
    - '#/content/application~1json/example/action'
    - '#/content/application~1json/example/client'
    - '#/content/application~1json/example/responseContent'
    - '#/content/application~1json/example/resultCode'
    - '#/content/application~1json/example/resultMessage'
model/response/client_registration_get_response.yaml:
  no-invalid-media-type-examples:
    - '#/content/application~1json/example/action'
    - '#/content/application~1json/example/client'
    - '#/content/application~1json/example/responseContent'
    - '#/content/application~1json/example/resultCode'
    - '#/content/application~1json/example/resultMessage'
model/response/client_registration_update_response.yaml:
  no-invalid-media-type-examples:
    - '#/content/application~1json/example/action'
    - '#/content/application~1json/example/client'
    - '#/content/application~1json/example/responseContent'
    - '#/content/application~1json/example/resultCode'
    - '#/content/application~1json/example/resultMessage'
model/response/client_registration_delete_response.yaml:
  no-invalid-media-type-examples:
    - '#/content/application~1json/example/action'
    - '#/content/application~1json/example/resultCode'
    - '#/content/application~1json/example/resultMessage'
model/response/backchannel_authentication_response.yaml:
  no-invalid-media-type-examples:
    - '#/content/application~1json/example/action'
    - '#/content/application~1json/example/clientId'
    - '#/content/application~1json/example/clientIdAliasUsed'
    - '#/content/application~1json/example/clientName'
    - '#/content/application~1json/example/clientNotificationToken'
    - '#/content/application~1json/example/deliveryMode'
    - '#/content/application~1json/example/hint'
    - '#/content/application~1json/example/hintType'
    - '#/content/application~1json/example/requestedExpiry'
    - '#/content/application~1json/example/scopes'
    - '#/content/application~1json/example/serviceAttributes'
    - '#/content/application~1json/example/ticket'
    - '#/content/application~1json/example/userCode'
    - '#/content/application~1json/example/userCodeRequired'
    - '#/content/application~1json/example/resultCode'
    - '#/content/application~1json/example/resultMessage'
model/response/backchannel_authentication_issue_response.yaml:
  no-invalid-media-type-examples:
    - '#/content/application~1json/example/action'
    - '#/content/application~1json/example/authReqId'
    - '#/content/application~1json/example/expiresIn'
    - '#/content/application~1json/example/interval'
    - '#/content/application~1json/example/responseContent'
    - '#/content/application~1json/example/resultCode'
    - '#/content/application~1json/example/resultMessage'
model/response/backchannel_authentication_fail_response.yaml:
  no-invalid-media-type-examples:
    - '#/content/application~1json/example/action'
    - '#/content/application~1json/example/responseContent'
    - '#/content/application~1json/example/resultCode'
    - '#/content/application~1json/example/resultMessage'
model/response/backchannel_authentication_complete_response.yaml:
  no-invalid-media-type-examples:
    - '#/content/application~1json/example/accessTokenDuration'
    - '#/content/application~1json/example/action'
    - '#/content/application~1json/example/authReqId'
    - '#/content/application~1json/example/clientId'
    - '#/content/application~1json/example/clientIdAliasUsed'
    - '#/content/application~1json/example/clientName'
    - '#/content/application~1json/example/deliveryMode'
    - '#/content/application~1json/example/idTokenDuration'
    - '#/content/application~1json/example/refreshTokenDuration'
    - '#/content/application~1json/example/serviceAttributes'
    - '#/content/application~1json/example/resultCode'
    - '#/content/application~1json/example/resultMessage'
model/response/device_verification_response.yaml:
  no-invalid-media-type-examples:
    - '#/content/application~1json/example/action'
    - '#/content/application~1json/example/clientId'
    - '#/content/application~1json/example/clientIdAliasUsed'
    - '#/content/application~1json/example/clientName'
    - '#/content/application~1json/example/expiresAt'
    - '#/content/application~1json/example/scopes'
    - '#/content/application~1json/example/serviceAttributes'
    - '#/content/application~1json/example/resultCode'
    - '#/content/application~1json/example/resultMessage'
model/response/device_complete_response.yaml:
  no-invalid-media-type-examples:
    - '#/content/application~1json/example/action'
    - '#/content/application~1json/example/resultCode'
    - '#/content/application~1json/example/resultMessage'
model/response/token_create_response.yaml:
  no-invalid-media-type-examples:
    - '#/content/application~1json/example/accessToken'
    - '#/content/application~1json/example/action'
    - '#/content/application~1json/example/clientId'
    - '#/content/application~1json/example/expiresAt'
    - '#/content/application~1json/example/expiresIn'
    - '#/content/application~1json/example/grantType'
    - '#/content/application~1json/example/refreshToken'
    - '#/content/application~1json/example/scopes'
    - '#/content/application~1json/example/subject'
    - '#/content/application~1json/example/tokenType'
    - '#/content/application~1json/example/resultCode'
    - '#/content/application~1json/example/resultMessage'
model/response/token_update_response.yaml:
  no-invalid-media-type-examples:
    - '#/content/application~1json/example/accessToken'
    - '#/content/application~1json/example/accessTokenExpiresAt'
    - '#/content/application~1json/example/action'
    - '#/content/application~1json/example/scopes'
    - '#/content/application~1json/example/tokenType'
    - '#/content/application~1json/example/resultCode'
    - '#/content/application~1json/example/resultMessage'
model/response/jose_verify_response.yaml:
  no-invalid-media-type-examples:
    - '#/content/application~1json/example/signatureValid'
    - '#/content/application~1json/example/valid'
    - '#/content/application~1json/example/resultCode'
    - '#/content/application~1json/example/resultMessage'
authlete-api.yaml:
  spec:
    - '#/components/APIResultCode'
